name: spefit
channels:
  - conda-forge
  - numba
dependencies:
  - anaconda-client
  - scipy
  - numpy
  - matplotlib
  - tqdm
  - numba>=0.50.1
  - iminuit>=1.4.9
  - pytest
  - tbb  # numba threading
  - icc_rt  # Intel SVML
